# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  - name: News
    url: '#news'
    weight: 40
  - name: Research Topics
    url: '#interest'
    weight: 41
  - name: Prospective Students
    url: '#students'
    weight: 42
  - name: Recent Publications
    url: '#publications'
    weight: 50
  - name: Preprint Papers
    url: '#preprints'
    weight: 51
  - name: Teaching Experience
    url: '#teaching'
    weight: 58
  - name: Awards
    url: '#awards'
    weight: 59
  - name: Services
    url: '#services'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 61

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/JWZhangCV2411.pdf
    weight: 70
